issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:Pinguteca/sdk-core-dotnet:ref:refs/heads/main"
claim_pattern:
  workflow_ref: "Pinguteca/sdk-core-dotnet/\\.github/workflows/img-optimization\\.yml@refs/heads/main"
permissions:
  contents: write
  pull_requests: write
